
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker

  node:
    image: node:22
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://docker:docker@mongodb:27017/db?authSource=admin
      MONGODB_URI_TEST: mongodb://docker:docker@mongodb:27017/dbtest?authSource=admin

  prism:
    image: stoplight/prism:4
    ports:
      - '4000:4000'
    volumes:
      - ./src/config/swagger.json:/app/swagger.json
    command: 'mock /app/swagger.json -p 4000'