
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker

  node:
    image: node:22
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://docker:docker@mongodb:27017/db?authSource=admin
